### ISSUE TITLE
Warning caused by repeater field values

### ISSUE THREAD

**Issue by diehenne** [fikaproductions/fika-gatsby-source-cockpit#10]
Hi, I'm getting a warning caused by my repeater-field and can't query any value. Is the repeater-field already supported in your plugin?

**Warning:**
> warning There are conflicting field types in your data. **GraphQL schema will omit those fields.**
> CockpitPages.content.value[].value:
>  - type: object
>    value: { imageField: [Object] }
>  - type: string
>    value: 'Some second content blablaa.'

Edit:
**Options JSON of Repeater:**
```
{
  "fields": [
    {
      "type": "textarea",
      "name": "textField",
      "label": "Text"
    },
    {
      "type": "set",
      "name": "addGalleryField",
      "label": "Add Gallery",
      "options": {
        "fields": [
          {
            "type": "text",
            "name": "galleryTitleField",
            "label": "Gallery Title"
          },
          {
            "type": "gallery",
            "name": "galleryField",
            "label": "New Gallery"
          }
        ]
      }
    },
    {
      "type": "set",
      "name": "addImageField",
      "label": "Add Image",
      "options": {
        "fields": [
          {
            "type": "text",
            "name": "imageTitleField",
            "label": "Image Title"
          },
          {
            "type": "image",
            "name": "imageField",
            "label": "New Image"
          }
        ]
      }
    }
  ]
}
```
Thanks

**Comment by DigitalGoldfish** [comment]
There are two different "modes" in which a repeater field can operate - a repeater where each field has the same type/structure or a repeater where entries might have a different structure from each other. The above described use case is the second - trickier - use case as GraphQL does not allow for differying value types. 

In Order to support this use case I guess every entry needs to be wrapped in a wrapper object like this

```
{
  type: "addGalleryField",
  addGalleryField: { ... },
  addImageField: null,
  textField: null
}
```

**Comment by diehenne** [comment]
This is wonderful, thank you guys. Where is your donation button ;)?

**Comment by WhippetsAintDogs** [comment]
@diehenne Haha, it is at the top of the web page, it's written "Star" on it ;)

**Comment by WhippetsAintDogs** [comment]
@diehenne Repeater are now integrated in version 1.0.13+.
