### ISSUE TITLE
Support for hierarchical collections

### ISSUE THREAD

**Issue by DigitalGoldfish** [fikaproductions/fika-gatsby-source-cockpit#11]
Cockpit allows to arrange collection entries in a hierarchical structure

![image](https://user-images.githubusercontent.com/559330/51141942-d6172b80-184a-11e9-9a41-cbbce00841b9.png)

The current implementation of the source plugin however will only create nodes for the root items. I've implemented support for reading the full hierarchical structure in my fork. If this feature is of interest I can prepare a pull request.

**Comment by DigitalGoldfish** [comment]
Here's how it looks in GraphQL

![image](https://user-images.githubusercontent.com/559330/51142628-c862a580-184c-11e9-991e-b049434eb427.png)

**Comment by WhippetsAintDogs** [comment]
Hi @DigitalGoldfish, I wasn't aware that you could do that with collection entries ☺ Could you walk me through how to reproduce that in Cockpit? And what version of Cockpit are you running? Definitively, your PR will be welcomed ☺

**Comment by DigitalGoldfish** [comment]
Hi @WhippetsAintDogs !

I am running an older (and somewhat customized) version of Cockpit but this feature is present in the latest cockpit release. All you have to do is to enable "Custom sortable entries" in the collection settings. Afterwards you can use drag & drop to sort the entries ... if instead of moving them up and down you drag them left or right you can organize them hierarchically.

I also discovered this accidently while sorting ... I am not sure if it is documented anywhere.

**Comment by WhippetsAintDogs** [comment]
Wow haha, cool discovery 😂 I had never quite understood that "Custom sortable entries" option before. I'll be waiting for your PR, thanks for contributing @DigitalGoldfish !
