### ISSUE TITLE
"Cockpit" type prefix no longer unique with support for singletons, ...

### ISSUE THREAD

**Issue by DigitalGoldfish** [fikaproductions/fika-gatsby-source-cockpit#18]
With the implementation of support for additional Cockpit entity types we might see the situation where the current typePrefix "Cockpit" might not be unique enough as e.g. there might be a collection with the name Contact and a singleton with the same name leading two two different GraphQL Types with the same name and an inevitable schema conflict. 

**Solution 1:** Use different type prefixes (e.g. CockpitCollection, CockpitSingleton, ...); easy to implement but would be a breaking change.
**Solution 2:** Detect name clashes in the plugin (also not hard to implement) and automatically rename the problematic entity. It would be possible to also specify an alias mapping in the config in case yomeone isn't happy with the automatic renaming. 

Votes? Alternative suggestions?

**Comment by WhippetsAintDogs** [comment]
I think the second solution is the best, it will be less "breaking change". By default (when there is no mapping in the config), I suggest we only add a suffixes to the name clashing entities. E.g. : CockpitPotatoes →CockpitPotatoesCollection / CockpitPotatoesSingleton.

**Comment by WhippetsAintDogs** [comment]
Support for aliasing Singletons and Collections and name clashes dectection added in version 1.1.0+. Closing this issue.
