### ISSUE TITLE
Add support for the Object field type

### ISSUE THREAD

**Issue by DigitalGoldfish** [fikaproductions/fika-gatsby-source-cockpit#19]
The object field type allows to specify a JSON object of arbitrary shape. This field needs to be implemented similar to the Layout field type as that the whole JSON Object needs to be stored as is without any field type inference from Gatsby(see extend-field-type.js) for how it is done for Layout.

Contrary to the Layout no further processing is required.

**Comment by WhippetsAintDogs** [comment]
Support for Objects added in version 1.0.14+. Closing this issue.
