### ISSUE TITLE
TypeError: Cannot destructure property `absolutePath` of 'undefined' or 'null'

### ISSUE THREAD

**Issue by ta-im-ok** [fikaproductions/fika-gatsby-source-cockpit#2]
Trying to configure this plugin with the latest Cockpit.
Configure @fika/gatsby-source-cockpit, and install the related plugins.
Run gatsby develop and get this error:
error Plugin @fika/gatsby-source-cockpit returned an error

  TypeError: Cannot destructure property `absolutePath` of 'undefined' or 'null'.

  - gatsby-node.js:63 copyFileToStaticFolder
    [cockpitgapp]/[@fika]/gatsby-source-cockpit/gatsby-node.js:63:32

  - gatsby-node.js:37 Object.exports.sourceNodes
    [cockpitgapp]/[@fika]/gatsby-source-cockpit/gatsby-node.js:37:31

error UNHANDLED REJECTION

  TypeError: Cannot read property 'filter' of undefined

  - api-runner-node.js:287 Promise.mapSeries.catch.then.results
    [cockpitgapp]/[gatsby]/dist/utils/api-runner-node.js:287:42

  - util.js:16 tryCatcher
    [cockpitgapp]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [cockpitgapp]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [cockpitgapp]/[bluebird]/js/release/promise.js:569:18

  - promise.js:614 Promise._settlePromise0
    [cockpitgapp]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [cockpitgapp]/[bluebird]/js/release/promise.js:694:18

  - async.js:138 _drainQueueStep
    [cockpitgapp]/[bluebird]/js/release/async.js:138:12

  - async.js:131 _drainQueue
    [cockpitgapp]/[bluebird]/js/release/async.js:131:9

  - async.js:147 Async._drainQueues
    [cockpitgapp]/[bluebird]/js/release/async.js:147:5

  - async.js:17 Immediate.Async.drainQueues
    [cockpitgapp]/[bluebird]/js/release/async.js:17:14
Environment
  System:
    OS: macOS 10.14
    CPU: x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 2.7.1 - /usr/local/bin/fish
  Binaries:
    Node: 10.9.0 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 70.0.3538.77
    Firefox: 63.0
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.37 => 2.0.37 
    gatsby-image: ^2.0.19 => 2.0.19 
    gatsby-plugin-favicon: ^3.1.4 => 3.1.4 
    gatsby-plugin-manifest: ^2.0.7 => 2.0.7 
    gatsby-plugin-offline: ^2.0.11 => 2.0.11 
    gatsby-plugin-react-helmet: ^3.0.1 => 3.0.1 
    gatsby-plugin-sharp: ^2.0.11 => 2.0.11 
    gatsby-plugin-styled-components: ^3.0.1 => 3.0.1 
    gatsby-plugin-typography: ^2.2.1 => 2.2.1 
    @fika/gatsby-source-cockpit: ^1.0.4 => 1.0.4 
    gatsby-source-filesystem: ^2.0.7 => 2.0.7 
    gatsby-transformer-sharp: ^2.1.7 => 2.1.7 
  npmGlobalPackages:
    gatsby-cli: 2.4.4

**Comment by WhippetsAintDogs** [comment]
Thanks for reporting that ! 

It seems like you have *Image fields* in your Cockpit collections which is currently supported by the plugin. But, it's the way of attaching the image to the entry that causes the problem. I've made sure that attaching a image using the "Select asset" or "Image URL" options both works, but not the "Select image" because I couldn't see the use case for it. Meanwhile, as a workaround, try importing images from the asset manager ("Select asset") instead of using the "Select image" option. I'll add support for it soon.

**Comment by ta-im-ok** [comment]
Thank you for you very quick and spot on response. I can confirm that your diagnosis and the described remedy works.
Everything now works as it should.

**Comment by artndes9** [comment]
Facing the same problem with gallery field..
can't say the workaround solves the problem.

**Comment by WhippetsAintDogs** [comment]
The *Gallery field* isn't supported right now, coming soon ;)

**Comment by WhippetsAintDogs** [comment]
@ta-im-ok Importing images using "Select image" should now be working for version +1.0.5.

**Comment by WhippetsAintDogs** [comment]
@artndes9 The _Gallery field type_ should now be working for version +1.0.6.
