### ISSUE TITLE
error Plugin @fika/gatsby-source-cockpit returned an error

### ISSUE THREAD

**Issue by Hypothesis-github** [fikaproductions/fika-gatsby-source-cockpit#30]
I have 2 types of error first is generated with

`baseUrl:: "http://domain.com/cockpit",`

and is

```
 error Plugin @fika/gatsby-source-cockpit returned an error


  Error: Token config parameter is invalid

  - CockpitService.js:45 CockpitService.validateToken
    [gatsby-cockpit]/[@fika]/gatsby-source-cockpit/src/CockpitService.js:45:13
```
second one I change the URL and I add a / at the end

`baseUrl:: "http://domain.com/cockpit/",`

and it turns into

```
error Plugin @fika/gatsby-source-cockpit returned an error


  TypeError: names.filter is not a function

  - CockpitService.js:91 CockpitService.getCollections
    [gatsby-cockpit]/[@fika]/gatsby-source-cockpit/src/CockpitService.js:91:10


```
please guide me.

**Comment by WhippetsAintDogs** [comment]
Hi @Hypothesis-github!

The `baseUrl` you should set in your plugin configuration is:  `http://hfp.co.ir/cockpit`, with no `/` at the end. Did you tried that ? If so, what was the output ?

**Comment by DigitalGoldfish** [comment]
` TypeError: names.filter is not a function`

We should add a check if names is an array and not empty here and either ignore it (no collections might happen once we support singletons) or throw a more appropriate error if we can detect that there is no Cockpit Instance available at that URL..
