### ISSUE TITLE
wysiwyg inserted photo does not show up

### ISSUE THREAD

**Issue by Hypothesis-github** [fikaproductions/fika-gatsby-source-cockpit#35]
wysiwyg contains an image ( inserted into the editor ) and I cannot retrieve it by using 
```

        Description{
          value
        }
```

Description is wysiwyg type. However, I am able to easily retrieve the text and sizes.

**Comment by WhippetsAintDogs** [comment]
Hi @Hypothesis-github, Wysiwyg type is just not currently implemented (except for the trivial stuff such as texts). 

Cit: 
```
Actually, it supports querying raw texts (and any trivial field types), Markdown, images, galleries, assets, sets, repeaters, layout(-grid)s (currently only without nested images/assets), objects, linked collections and internationalization.
```

Feel free to contribute and submit a PR if you have some spare time :)
