### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by Hypothesis-github** [fikaproductions/fika-gatsby-source-cockpit#38]
For some reason, if you set the type as TAGS, you cannot retrieve Value in graphql.

any workaround this ?

**Comment by Grunt-139** [comment]
Does your tag field have a value within your entry?

I just spent quite a bit of time trying to figure out why fields were not showing up, when I realized the fields were empty in all of my entries. As soon as I gave it a value in one of my entries, it popped up.

Not sure if this will help or not but thought I would share in case it helps.

**Comment by WhippetsAintDogs** [comment]
@Hypothesis-github, did you find the reason why you had that problem ?

**Comment by WhippetsAintDogs** [comment]
Closed due to the lack of activity.
